# Generated by Django 4.2.15 on 2024-09-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcceptedWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="NextBestGuess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_words", models.TextField()),
                ("next_best_word", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="PossibleWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
