name: Wordle-Solver CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    environment: QA  # Replace with your GitHub environment name

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and deploy
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_DEBUG: ${{ vars.DJANGO_DEBUG }}
        DJANGO_ALLOWED_HOSTS: ${{ vars.DJANGO_ALLOWED_HOSTS }}
        MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ vars.DB_PORT }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_USER: ${{ vars.DB_USER }}
      run: |
        docker compose down
        docker compose up --build -d

  sonar:
    name: SonarCube Analysis
    runs-on: self-hosted
    environment: QA
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
