name: Wordle-Solver CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Build and deploy
      run: |
        docker compose down
        docker compose up --build -d
